#! /bin/sh

# Starts picom, for blurry/transparent windows BREAKS IT FOR SOME REASON
# picom --config ~/.config/picom/picom.conf

# Starts sxhkd, a hotkey daemon typically used for tiling window managers
sxhkd &

# Sets the wallpaper and changes terminal colors to match the most prominent colors in the image by using wal
wal -i /home/user/Pictures/wallpaperflare.com_wallpaper.jpg

# Starts polybar, a highly configurable task/status bar
polybar main &

# picom --config ~/.config/picom/picom.conf NOT HERE EITHER

# bspwm configuration
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

xrdb ~/.Xresources

picom --conf ~/.config/picom/picom.conf
